name: CD
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'some message'     
        required: true
        default: 'hi'
      another:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, world!
      - run: echo "message = ${{message}}"
