name: CD

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'some message'     
        required: true
        default: 'hi'
      another:
        description: 'Another param'
        required: false
        default: 'Mona the Octocat'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, world!
      - run: echo "message = ${{github.event.inputs.message}}"
