name: CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'     
        required: true
#         default: '[Nothing]'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Preaparing to deploy to ${{github.event.inputs.environment}}"
          
  qa:
    needs: setup
    if: ${{github.event.inputs.environment}} == "QA"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying "
      - run: echo "Running integration tests"
      - run: echo "Publishing release package"

  staging:
    needs: setup
    if: ${{github.event.inputs.environment}} == "STG"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying"
      - run: echo "Running load tests"

  production:
    needs: setup
    if: ${{github.event.inputs.environment}} == "PROD"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying"
      - run: echo "Running smoke tests"
